// Automatically generated by assembler, do not edit.
#define OP_NOP               0
#define OP_JMP               1
#define OP_HLT               2
#define OP_L                 3
#define OP_LB                4
#define OP_LI                5
#define OP_W                 6
#define OP_WB                7
#define OP_INC               8
#define OP_DEC               9
#define OP_OUT               10
#define OP_JEQ               11
#define OP_JNE               12
#define OP_AND               13
#define OP_OR                14
#define OP_XOR               15
#define OP_ADD               16
#define OP_SUB               17
#define OP_MUL               18
#define OP_DIV               19
#define OP_WRT               20

const char *opnames[]={"nop", "jmp", "hlt", "l", "lb", "li", "w", "wb", "inc", "dec", "out", "jeq", "jne", "and", "or", "xor", "add", "sub", "mul", "div", "wrt"};
